// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

function add$prime(x, y) {
  return x + y | 0;
}

function add1(param) {
  return 1 + param | 0;
}

exports.add = add;
exports.add$prime = add$prime;
exports.add1 = add1;
/* No side effect */
